version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=firmadigital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - db2:/var/lib/postgresql/data
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.5
    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=juank20097@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pg2:/var/lib/pgadmin
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.6
    
  ws-firmaec:
    image: spring/firmaec_ws
    container_name: ws-firmaec
    restart: always
    depends_on:
      - mintel-firmaec
      - postgres
    ports:
      - 8090:8090
    environment:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://172.29.0.5:5432/firmadigital
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - server.port=8090
      - spring.jpa.hibernate.ddl-auto=update
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.3

  mintel-firmaec:
    image: jboss/wildfly-admin
    container_name: mintel-firmaec
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9990:9990
    networks:
      network_firmaec:
        ipv4_address: 172.29.0.2

volumes:
  db2:
    driver: local
  pg2:
    driver: local

networks:
  network_firmaec:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          ip_range: 172.29.0.0/24
          gateway: 172.29.0.254
